### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by urchykli** [CSIS-iLab/nuclearnetwork_wp#96]
- [x] Authors with no title shouldn't have "-" after their name.
- [x] Event subtypes aren't showing on post blocks.
- [x] Author section in post footer is overflowing the container.
- [x] On small screens, the content type overlaps the image on the post block (LU)
- [x] Archive filters aren't filtering.
- [x] Blockquotes add HTML tag at beginning of quote
- [ ] On the [post block](https://csisngnndev.wpengine.com/analysis/), sometimes a single author is listed with " and " after their name.
- [x] Series and general archive pages are missing header image. (LU)
- [x] Archive filters add checkboxes when you use the pagination to navigate.
- [x] Related post blocks on single posts
     - [x] Remove "Published"
     - [x] Date and Author should be side by side
     - [x] There should only be one column
     - [x] The title needs to be aligned with the rest of the content

**Comment by christina-designs** [comment]
Looking good!  Much closer!

Some things I've found (and if you don't see it, it's maybe because of my caching, so it's probably on my end in that case):

- [ ] Post header max width is 900px
- [ ] Post footer for non-analysis posts (including the program page) should be empty and look like the bottom of the About page (with a little bit of gray between the white section and the page footer) 
![image](https://user-images.githubusercontent.com/67332530/133842477-161c21e5-666a-4731-93ea-c4876e1b94d9.png)
- [ ] Download and text buttons should be centered on the page
- [ ] Page footer content background seems to be set to a fill instead of transparent (seeing solid Blue-100 instead of the gradient)
- [ ] About page Career Opps section gray background shouldn't be full screen width, but should be the same width as the white background.
- [ ] Project pages should have "Project" next to the yellow dash line at the top, like on the Programs pages
- [ ]
